all:
  hosts:
    web.mydomain.local:
  children:
    db:
      hosts:
        db1.mydomain.local:
        db2.mydomain.local:
        db3.mydomain.local:
    web:
      hosts:
        web1.mydomain.local:
        web2.mydomain.local:
        web3.mydomain.local:

    customer1:
      children:
        db:
          hosts:
            db1.mydomain.local:
            db2.mydomain.local:
            db3.mydomain.local:
        web:
          hosts:
            web1.mydomain.local:
            web2.mydomain.local:
            web3.mydomain.local:
