all:
  hosts:
    mail.mycorp.local:
    smtp.mycorp.local:
    auth.mycorp.local:
  children:
    dc:
      children:
        dc01.mycorp.local:
        dc02.mycorp.local:
    itlappsrv:
      children:
        ldn:
          hosts:
            app01.ldn.mycorp.local:
            app02.ldn.mycorp.local:
        tx:
          hosts:
            app03.tx.mycorp.local:
            app04.tx.mycorp.local: